var weekIndex = localStorage.getItem('weekIndex')
if (weekIndex === null) localStorage.setItem('weekIndex', '0')
weekIndex = Number(localStorage.getItem('weekIndex'))

var timeOffset = localStorage.getItem('timeOffset')
if (timeOffset === null) localStorage.setItem('timeOffset', '0')
timeOffset = Number(localStorage.getItem('timeOffset'))

var dayOffset = localStorage.getItem('dayOffset')
if (dayOffset === null) localStorage.setItem('dayOffset', '-1')
dayOffset = Number(localStorage.getItem('dayOffset'))

var setDayOffsetLastDay = localStorage.getItem('setDayOffsetLastDay')
if (setDayOffsetLastDay === null) localStorage.setItem('setDayOffsetLastDay', '-1')
setDayOffsetLastDay = Number(localStorage.getItem('setDayOffsetLastDay'))



/**
 * 获取根据计时偏移量矫正后的当前日期对象
 * @returns {Date} 矫正后的 Date 对象
 */
function getCurrentEditedDate() {
    let d = new Date();
    d.setSeconds(d.getSeconds() + timeOffset)
    return d;
}

/**
 * 获取矫正后的当前星期索引（0-6）
 * 处理日期偏移逻辑，如果不是当天设置的偏移则重置
 * @param {Date} date - 当前日期对象
 * @returns {number} 星期索引
 */
function getCurrentEditedDay(date) {
    if (dayOffset === -1)
        return date.getDay();
    if (setDayOffsetLastDay == new Date().getDay()) {
        return dayOffset;
    }
    localStorage.setItem('dayOffset', '-1')
    localStorage.setItem('setDayOffsetLastDay', '-1')
    dayOffset = -1
    setDayOffsetLastDay = -1
    return date.getDay();
}

// Generated by ChatGPT4 
/**
 * 判断当前时间是否在指定的休息时间内
 * @param {string} startTime - 开始时间 (HH:MM)
 * @param {string} endTime - 结束时间 (HH:MM)
 * @param {string} currentTime - 当前时间 (HH:MM)
 * @returns {boolean}
 */
function isBreakTime(startTime, endTime, currentTime) {
    const [startH, startM] = startTime.split(':').map(Number);
    const [endH, endM] = endTime.split(':').map(Number);
    const [currentH, currentM] = currentTime.split(':').map(Number);

    const startMinutes = startH * 60 + startM;
    const endMinutes = endH * 60 + endM;
    const currentMinutes = currentH * 60 + currentM;

    return currentMinutes >= startMinutes && currentMinutes <= endMinutes;
}

// Generated by ChatGPT4 
/**
 * 获取当前节之后的第一节课的索引
 * @param {Object} timetable - 时间表对象
 * @param {number} currentIndex - 当前遍历到的索引
 * @returns {number|null} 课程索引或 null
 */
function getNextClassIndex(timetable, currentIndex) {
    // 从当前时间点的下一个时间段开始，找到下一个课程的索引
    const timeKeys = Object.keys(timetable);
    for (let i = currentIndex + 1; i < timeKeys.length; i++) {
        if (typeof timetable[timeKeys[i]] === 'number') {
            return timetable[timeKeys[i]];
        }
    }
    return null; // 如果没有下一堂课，返回 null
}

// Generated by ChatGPT4 
/**
 * 获取当天的课程列表
 * 根据当前周数处理单双周课程
 * @returns {Array} 课程名称数组
 */
function getCurrentDaySchedule() {
    const date = getCurrentEditedDate();
    const dayOfWeek = getCurrentEditedDay(date); // 0 = Sunday, 1 = Monday, ...
    const weekNumber = weekIndex; // 当前周数
    const dailyClass = scheduleConfig.daily_class[dayOfWeek];
    if (!dailyClass) return [];
    return dailyClass.classList.map(subject => {
        if (Array.isArray(subject)) {
            return subject[weekNumber]; // 处理每周不同的课程
        }
        return subject;
    });
}

// Generated by ChatGPT4 
/**
 * 判断当前时间是否属于某节课的时间段
 * @param {string} startTime - 开始时间
 * @param {string} endTime - 结束时间
 * @param {string} currentTime - 当前时间
 * @returns {boolean}
 */
function isClassCurrent(startTime, endTime, currentTime) {
    const [startH, startM] = startTime.split(':').map(Number);
    const [endH, endM] = endTime.split(':').map(Number);
    const [currentH, currentM] = currentTime.split(':').map(Number);

    const startMinutes = startH * 60 + startM;
    const endMinutes = endH * 60 + endM;
    const currentMinutes = currentH * 60 + currentM;

    return currentMinutes >= startMinutes && currentMinutes <= endMinutes;
}

// Generated by ChatGPT4 
/**
 * 获取格式化后的当前时间字符串
 * @returns {string} HH:MM:SS 格式的时间
 */
function getCurrentTime() {
    const now = getCurrentEditedDate();
    return [
        now.getHours().toString().padStart(2, '0'),
        now.getMinutes().toString().padStart(2, '0'),
        now.getSeconds().toString().padStart(2, '0')
    ].join(':');
}

// Generated by ChatGPT4 
/**
 * 获取完整的课表渲染数据
 * 计算当前应该高亮的课程及其倒计时状态
 * @returns {Object} 包含 scheduleArray, currentHighlight, timetable, divider
 */
function getScheduleData() {
    const currentSchedule = getCurrentDaySchedule();
    const currentTime = getCurrentTime();
    // let currentTime = '07:10:01';
    const dayOfWeek = getCurrentEditedDay(getCurrentEditedDate());
    const timetable = scheduleConfig.daily_class[dayOfWeek].timetable
    const dayTimetable = scheduleConfig.timetable[timetable];
    const divider = scheduleConfig.divider[timetable];
    let scheduleArray = [];
    let currentHighlight = { index: null, type: null, fullName: null, countdown: null, countdownText: null };
    Object.keys(dayTimetable).forEach((timeRange, index) => {
        const [startTime, endTime] = timeRange.split('-');
        const classIndex = dayTimetable[timeRange];

        if (typeof classIndex === 'number') {
            const subjectShortName = currentSchedule[classIndex];
            const subjectFullName = scheduleConfig.subject_name[subjectShortName];
            scheduleArray.push(subjectShortName);

            if (isClassCurrent(startTime, endTime, currentTime)) {
                currentHighlight.index = scheduleArray.length - 1;
                currentHighlight.type = 'current';
                currentHighlight.fullName = subjectFullName;
                currentHighlight.countdown = calculateCountdown(endTime, currentTime);
                currentHighlight.countdownText = formatCountdown(currentHighlight.countdown);
            }
        } else if (currentHighlight.index === null && isBreakTime(startTime, endTime, currentTime)) {
            let highlighted = false;
            for (let i = index + 1; i < Object.keys(dayTimetable).length; i++) {
                const nextTimeRange = Object.keys(dayTimetable)[i];
                const nextClassIndex = dayTimetable[nextTimeRange];
                if (typeof nextClassIndex === 'number') {
                    currentHighlight.index = scheduleArray.length;
                    currentHighlight.type = 'upcoming';
                    const nextSubjectShortName = currentSchedule[nextClassIndex];
                    const nextSubjectFullName = scheduleConfig.subject_name[nextSubjectShortName];
                    currentHighlight.fullName = dayTimetable[timeRange];
                    const [nextStartTime] = nextTimeRange.split('-');
                    currentHighlight.countdown = calculateCountdown(timeRange.split('-')[1], currentTime);
                    currentHighlight.countdownText = formatCountdown(currentHighlight.countdown);
                    highlighted = true;
                    break;
                }
            }
            if (!highlighted) {
                currentHighlight.index = currentSchedule.length - 1;
                currentHighlight.type = 'upcoming';
                currentHighlight.fullName = dayTimetable[timeRange];
                currentHighlight.countdown = calculateCountdown(timeRange.split('-')[1], currentTime);
                currentHighlight.countdownText = formatCountdown(currentHighlight.countdown);
                currentHighlight.isEnd = true;
            }
        } else if (currentHighlight.index === null && !dayTimetable[timeRange]) {
            // 当前时间是非课程时间（如课间休息）
            currentHighlight.fullName = currentSchedule[classIndex]; // 使用时间表中的描述
        }
    });
    return { scheduleArray, currentHighlight, timetable, divider };
}


// Generated by ChatGPT4 
/**
 * 计算两个时间点之间的秒数差
 * @param {string} targetTime - 目标时间 (HH:MM)
 * @param {string} currentTime - 当前时间 (HH:MM:SS)
 * @returns {number} 差值秒数
 */
function calculateCountdown(targetTime, currentTime) {
    const [targetH, targetM] = targetTime.split(':').map(Number);
    const [currentH, currentM, currentS = '00'] = currentTime.split(':').map(Number);

    const targetTotalSeconds = targetH * 3600 + (targetM + 1) * 60;
    const currentTotalSeconds = currentH * 3600 + currentM * 60 + currentS;

    return targetTotalSeconds - currentTotalSeconds;
}

// Generated by ChatGPT4 
/**
 * 将秒数格式化为 MM:SS 倒计时字符串
 * @param {number} countdownSeconds - 秒数
 * @returns {string}
 */
function formatCountdown(countdownSeconds) {
    const minutes = Math.floor(countdownSeconds / 60);
    const seconds = countdownSeconds % 60;
    return `${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;
}

/**
 * 动态计算并设置countdownContainer的位置
 * 确保countdownContainer在globalContainer右边且水平居中对齐
 */
function setCountdownerPosition() {
    const globalContainer = document.getElementById('globalContainer');
    const countdownContainer = document.getElementById('countdownContainer');
    const countdowner = document.getElementById('countdowner');

    if (globalContainer && countdownContainer && countdowner) {
        // 获取globalContainer的宽度
        const globalWidth = globalContainer.offsetWidth;

        // 获取countdowner的宽度
        const countdownerWidth = countdowner.offsetWidth;

        // 计算countdownContainer应该距离globalContainer右边的距离
        // 使用margin-left而不是left定位，确保水平对齐
        const marginLeft = globalWidth + 20; // 20px的间距

        // 设置countdownContainer的位置
        countdownContainer.style.marginLeft = marginLeft + 'px';

        // 确保countdownContainer垂直居中
        countdownContainer.style.top = '50%';
        countdownContainer.style.transform = 'translateY(-50%)';
    }
}

// 页面加载完成后初始化位置
window.addEventListener('load', function () {
    setCountdownerPosition();

    // 监听窗口大小变化，动态调整位置
    window.addEventListener('resize', setCountdownerPosition);

    // 监听课程内容变化，动态调整位置
    // 这里可以添加对课程内容变化的监听
});



