name: Build and Release Electron App

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.6.0'

      - name: Install dependencies
        run: npm install
        shell: bash

      - name: Build Electron App
        run: npm run build
        shell: bash

      - name: Get version from package.json
        id: pkg
        shell: bash
        run: |
          VERSION=$(node -e "console.log(require('./package.json').version)")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Generate tag
        id: tag
        shell: bash
        run: |
          SHORT_SHA=${GITHUB_SHA::5}
          TAG="v${VERSION}-${SHORT_SHA}"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "Generated tag: $TAG"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: Release ${{ env.TAG }}
          draft: false
          prerelease: false
          files: out/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
